#!/usr/bin/env bash
# short version: configures a server to run and listen on port 80 of all the server’s active IPv4 IPs
sudo sed -i -e 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo pkill -o nginx
